OrdererOrgs:
  - Name: Orderer
    Domain: freelancerDomain.com
    Specs:
      - Hostname: orderer1
      - Hostname: orderer2

PeerOrgs:
  - Name: Prog
    Domain: prog.freelancerDomain.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Design
    Domain: design.freelancerDomain.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Cert
    Domain: cert.freelancerDomain.com
    Template:
      Count: 2
    Users:
      Count: 1